project:
  type: website

website:
  title: "ADSN2026"
  navbar:
    left:
      - text: Program
        menu: 
          - text: Keynotes
            href: keynotes.qmd
          # - text: Schedule
          #   href: schedule.qmd
          - text: Abstract Submission
            href: abstract.qmd
      - text: Participation
        menu: 
          - text: Registration
            href: registration.qmd
          - text: "Location and Accommodation"
            href: accommodation.qmd
      - text: Sponsorship
        href: sponsors.qmd
      - text: About
        menu: 
          - text: Organisers
            href: organisers.qmd
          # - text: "Code of Conduct"
          #   href: codeofconduct.qmd
    tools:
    - icon: github
      url: https://github.com/ausdatascinet/conference-2026

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    link-external-newwindow: true

editor: visual

