project:
  type: website

website:
  title: "ADSN2026"
  open-graph:
    image-alt: "A panoramic photograph of Canberra, Australia, showing the central city area, surrounding lakes, and the parliamentary triangle"
    image: "/img/canberra.jpg"
  navbar:
    left:
      - text: Program
        href: program.qmd
      - text: Destination
        href: destination.qmd
      - text: Abstract Submission
        href: abstract.qmd
      - text: Registration
        href: registration.qmd
      - text: Sponsorship
        href: sponsors.qmd
      - text: About
        menu: 
          - text: Organisers
            href: organisers.qmd
          # - text: "Code of Conduct"
          #   href: codeofconduct.qmd
    tools:
    - icon: github
      url: https://github.com/ausdatascinet/conference-2026
  page-footer:
    left: |
      Presenting Partners
      
      [![](img/adsn.jpg){width=100px}](https://australiandatascience.net/)
      [![](img/ssa.png){width=100px}](https://statsoc.org.au/)
    center: |
      Thanks to our sponsors
      
      [![](img/abs.png){width=100px}](https://www.abs.gov.au/)
    background: "#f8f9fa"
    

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    link-external-newwindow: true
    grid:
      sidebar-width: 300px
      body-width: 1000px
      margin-width: 200px
