---
title: "Abstract submission"
---

::: {style="font-size: 2rem; font-weight=600;"}
<p id="countdown"></p>

[Submit here](https://forms.gle/Si2vF1hyAd1BrJfr5)

:::

## Key information

The theme of the conference is "From Data to Decisions", however we invite submissions of abstracts for contributed talks and posters across all areas of data science, including but not limited to:

- Health and biomedical data science
- Data reuse, linkage, and secondary data sources
- Environmental and agricultural data science
- Statistical modelling, machine learning and AI
- Data visualisation, interpretability, and explainability
- Data platforms, tools and infrastructure
- Urban, geospatial and remote sensing analytics
- Ethics, privacy and data governance
- Digital humanities and social science
- Industry and government applications

Follow the [ADSN on LinkedIn](https://www.linkedin.com/company/australiandata/) or [subscribe to the newsletter](https://australiandatascience.net/subscribe-to-newsletter/) to stay up-to-date.



<script>
var countDownDate = new Date("Jul 25, 2026 11:59:59").getTime();

var x = setInterval(function() {

  // Get today's date and time
  var now = new Date().getTime();

  // Find the distance between now and the count down date
  var distance = countDownDate - now;

  // Time calculations for days, hours, minutes and seconds
  var days = Math.floor(distance / (1000 * 60 * 60 * 24));
  var hours = Math.floor((distance % (1000 * 60 * 60 * 24)) / (1000 * 60 * 60));
  var minutes = Math.floor((distance % (1000 * 60 * 60)) / (1000 * 60));
  var seconds = Math.floor((distance % (1000 * 60)) / 1000);

  // Display the result in the element with id="countdown"
  document.getElementById("countdown").innerHTML = "Closing in " + days + "d " + hours + "h "
  + minutes + "m " + seconds + "s ";

  // If the count down is finished, write some text
  if (distance < 0) {
    clearInterval(x);
    document.getElementById("countdown").innerHTML = "EXPIRED";
  }
}, 1000);
</script>