---
title: "Code of Conduct"
---

The organisers of the Australian Data Science Network Conference 2026 are committed to providing a conference that is welcoming and safe for all participants, is free from unlawful discrimination and harassment, and where all participants are treated with dignity and respect. Harassment is unlawful under both federal and all Australian state anti-discrimination laws, and as such, people suspected of such misconduct may be reported to authorities. Adherence to this Code of Conduct is a requirement for all conference participants and sponsors, and covers all aspects of this conference, including conference sessions and breaks, all social events and all communication, including that via
email or social media (including but not limited to Facebook and X (formerly Twitter)) associated with the conference. Unacceptable behaviour includes, but is not limited to:

- Harassment, including verbal comments relating to gender, sexual orientation, disability, race, ethnicity, religion, age, national origin, gender identity or expression, or physical appearance.
- Inappropriate and/or unwanted physical contact.
- Unwelcome sexual attention, which can include inappropriate questions of a sexual nature, asking for sexual favours or repeatedly asking for dates or contact information.
- Stalking or deliberate intimidation.
- Unwanted photography or recording (if you are asked to stop photographing or recording someone, please do so; if someone indicates that they do not want to be photographed or - recorded, do not record or photograph them).
- Discriminatory or sexual images in public spaces.
- Sustained or wilful disruption of talks or other events.

To report violations of this Code of Conduct, alert a member of the Response Team (names and contact details listed below). Reports may be made by people subject to, or witnesses of, unacceptable behaviour. 

## Code of Conduct Response Team

[In this section list the names, email addresses, and if appropriate, telephone numbers, of people tasked with responding to reports of violations of the Code. At least two people must be listed, but ideally there will be several listed contacts, from a variety of institutions/workplaces, including both men and women. The list should include, but is not limited to, conference/meeting organisers. Ideally members of this response team will have some training in dealing with reports of harassment.]

For example: Abba B Abbason, Senior Lecturer at Stats University. Email:…, Phone number:….

If an individual participates in unacceptable behaviour, the Response Team may take lawful action that they deem appropriate, including asking the individual to stop or removal of the individual from the [conference/event/meeting] without refund of registration and/or other applicable fees. Reports of unacceptable behaviour may be communicated to the Statistical Society of Australia, and individuals who participate in unacceptable behaviour may face consequences including being disallowed from attending future events. Individuals who are ejected will not be allowed to give any planned oral or poster presentations, and their place may be allocated to another attendee. The reason for the replacement presentation may also be announced (e.g., “Professor X has violated this event’s code of conduct and has been asked to leave and therefore will not be able to present today, in their place we will instead hear from ...”). Violations may be reported to the individual’s employer or research funders. Statistical Society of Australia members may have their membership cancelled without refund of membership fees.

All efforts will be made to protect the anonymity of persons reporting violations. Persons reporting violations of the Code may request that their report remain confidential and that no further action be taken. However, if the Code of Conduct Response Team deems it necessary for the safety of event attendees, action will be taken, including referral of the report to the Statistical Society of Australia. This Code of Conduct is designed to ensure that this event can be enjoyed by all participants.

We hope you have an inspiring and enjoyable time.