---
title: "Registration"
---

## Conference

Registrations for the conference are made through the [Statistical Society of Australia's website](https://statsoc.org.au/event-6727769).

Price structure:

- SSA members
  - Early bird $300
  - Standard $350
- Non-SSA members
  - Early bird $350
  - Standard $400
- Students
  - Early bird $150
  - Standard $175

**Early bird pricing closes 18th September.**

All registrations include attendance for both days of the conference and the conference social event. The pre-conference workshop requires separate registration, see below for more details.

Building security require **all conference attendees to bring a photo ID** in order to be provided access to the conference venue.

## Pre-conference workshop

The pre-confernece workshop, Modern Data Linkage Methods and Implementation Using Splink, is open for registrations! See the [workshop page](./workshop.qmd) for more details.

Follow the [ADSN on LinkedIn](https://www.linkedin.com/company/australiandata/) or [subscribe to the newsletter](https://australiandatascience.net/subscribe-to-newsletter/) to stay up-to-date.