---
title: "Schedule"
format:
  html:
    html-table-processing: none
execute:
  echo: false
  message: false
  warning: false
---

```{r}
library(readr)
library(dplyr)
library(lubridate)
library(gt)

abstracts <- read_csv("resources/abstracts.csv")

program <- read_csv("resources/program.csv", col_types = "ccccc") |>
  left_join(
    abstracts,
    by = c("theme"),
    relationship = "many-to-many",
  ) |>
  mutate(
    session = case_when(
      theme == "ardc" ~ session,
      !is.na(theme) ~ paste0(session, ": ", theme),
      .default = session
    ),
    category = factor(
      category,
      levels = c(
        "break",
        "keynote",
        "panel",
        "posters",
        "procedural",
        "social",
        "talks",
        "workshop"
      )
    ),
    duration = paste0(
      "(",
      time_length(
        parse_date_time(end, orders = "%I:%M %p") -
          parse_date_time(start, orders = "%I:%M %p"),
        unit = "minutes"
      ),
      "min)"
    ),
    session = paste0(session, " ", duration),
    title = case_when(
      !is.na(abstract) ~ paste0(
        title,
        "<br><br><details><summary>Abstract</summary>",
        "<div style='white-space:pre-wrap;'>",
        abstract,
        "</div>",
        "</details>"
      ),
      !is.na(name) ~ paste0(
        name,
        "<br><br><details><summary>Abstract</summary>",
        "<div style='white-space:pre-wrap;'>",
        description,
        "</div>",
        "</details>"
      ),
      .default = NA
    ),
    authors = case_when(
      !is.na(presenter) ~ presenter,
      .default = authors
    )
  )

make_program <- function(program_date) {
  program |>
    filter(date == program_date) |>
    select(
      start,
      category,
      session,
      title,
      authors
    ) |>
    gt(
      groupname_col = c("start", "session"),
    ) |>
    cols_hide(category) |>
    sub_missing(columns = c(title, authors), missing_text = "") |>
    tab_options(column_labels.hidden = TRUE) |>
    tab_style(
      style = css(height = "0px", padding = "0px", font.size = "0px"),
      locations = cells_body(rows = is.na(title))
    ) |>
    tab_style(
      style = css(
        border.bottom.color = "#DEDEDE",
        background.color = "#DEDEDE",
        font.weight = "700"
      ),
      locations = cells_row_groups()
    ) |>
    tab_style(
      style = css(white.space = "pre-wrap", vertical.align = "top"),
      locations = cells_body(columns = c(title, authors))
    ) |>
    tab_options(table.layout = "fixed") |>
    cols_width(
      title ~ pct(50),
      authors ~ pct(50),
    ) |>
    fmt_markdown(columns = c(title, authors))
}
```

Session allocations will be announced soon!

::: {.panel-tabset}
### Wednesday 25th

```{r}
make_program("25/11/2026")
```

### Thursday 26th

```{r}
make_program("26/11/2026")
```

### Friday 27th

```{r}
make_program("27/11/2026")
```

:::